package com.hhoss.ksid;

import com.hhoss.boot.App;
import com.hhoss.jour.Logger;
import com.hhoss.ksid.Seq;
import com.hhoss.lang.Num;

public class SeqTest {
	private static final Logger logger = Logger.get();    
	private static final String SF="%9$d %1$d-%2$02d-%3$02d %4$02d:%5$02d:%6$02d %7$d-%8$d";
    /**
     * @param lsn long seq generated by Seq.next();
     * @return str of appIns-ymd-hms-sn
     */
    public static String format(int[] f){
    	return String.format(SF,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],f[0]);
    }
    
    public static void test1(){
    	for(int i=0;i<3;i++){
    		long seq = Seq.next();
	    	logger.debug("seq:{} => {}",seq, format(Seq.meta(seq)));
    	}
    	for(int i=0;i<Num.S6*40-5;i++){Seq.next();}
    	for(int i=0;i<5;i++){
    		long seq = Seq.next();
	    	logger.debug("seq:{} => {}",seq, format(Seq.meta(seq)));
    	}
    }
    
    public static void test2(){
    	{
    		long seq = Seq.next();
	    	logger.debug("seq:{} => {}",seq, Seq.ymd(seq));
    	}
    	{
    		long seq = Seq.next();
	    	logger.debug("seq:{} => {}",seq, Seq.hms(seq));
    	}
     }
    
    public static void test18(){
 		logger.debug("next seq : {} ", Seq.num18());
 		for(int j=0;j<300;j++){
 			for(int i=0;i<300;i++){Seq.num18();}
 			logger.debug("next seq : {} ", Seq.num18());
 		}
    }
    public static void test24(){
 		logger.debug("next seq : {} ", Seq.num24());
  		for(int j=0;j<30000;j++){
 			for(int i=0;i<30000;i++){ Seq.num24();}
 			logger.debug("next seq : {} ",  Seq.num24());
 		}
     }

 
    public static void main(String[] args){
    	logger.debug("tims:{} => {}",System.currentTimeMillis()/1000);
    	App.defaultInitial();
//       	test1();
       	test2();
       	test18();
       	test24();
    }

}
