package com.hhoss.ksid;

import com.hhoss.jour.Logger;

public class SNIDTest {
	private static final Logger logger = Logger.get();    
	private static final String SF="%11$d-%1$d%2$02d%3$02d-%4$02d%5$02d%6$02d-%7$d.%8$d.%9$d.%10$d";
	private static final Idsn idsn=Idsn.get(0,0,0);

	/**
     * @param lsn long seq generated by Seq.next();
     * @return str of appIns-ymd-hms-sn
     */
    public static String restore(long lsn){
    	int[] f = Idsn.meta(lsn);
    	return String.format(SF,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],f[9],f[10],f[0]);
    }
    
    public static void test(){
    	for(int i=0;i<3;i++){
    		long seq = idsn.next();
	    	logger.debug("seq:{} => {}",seq, restore(seq));
    	}
    	for(int i=0;i<8192-5;i++)idsn.next();
    	for(int i=0;i<5;i++){
    		long seq = idsn.next();
	    	logger.debug("seq:{} => {}",seq, restore(seq));
    	}
    }
    

    public static void main(String[] args){
    	test();
    }

}
