package com.hhoss.ksid;

import com.hhoss.jour.Logger;
import com.hhoss.ksid.Tims;

public class TimsTest {
	private static final Logger logger = Logger.get();    
	private static final String SF="%7$d %1$d-%2$02d-%3$02d %4$02d:%5$02d:%6$02d";
    /**
     * @param lsn long seq generated by Seq.next();
     * @return str of appIns-ymd-hms-sn
     */
    public static String restore(int lsn){
    	int[] f = Tims.meta(lsn);
    	return String.format(SF,f[1],f[2],f[3],f[4],f[5],f[6],f[0]);
    }
    
    public static void testTims() throws Exception{
		int ts = Tims.get();
		logger.debug("tims:{} => {}",ts, restore(ts));
    	for(int i=0;i<1000_000;i++){
    	   	ts = Tims.get();
    	   	//restore(ts);
    	   	//SeqTims.meta(ts);
    	   	//System.out.print("");
        	//logger.debug("tims:{} => {}",ts, restore(ts));
        	//TimeUnit.MILLISECONDS.sleep(300);
    	}
		ts = Tims.get();
		logger.debug("tims:{} => {}",ts, restore(ts));
    }
 
    public static void main(String[] args) throws Exception{
     	testTims();
    }

}
