package com.hhoss.aspi;

import java.io.Serializable;
import java.util.Collection;
import java.util.Collections;

import com.hhoss.lang.Classes;

public interface Factory<S extends Serializable,F> {
	/**
	 * @return the factory name
	 */
	default String getName() {return Classes.referName();}
	/**
	 * @return the support names of generated instance
	 */
	@SuppressWarnings("unchecked")
	default Collection<S> supports(){
		return Collections.EMPTY_SET;
	}
	/**
	 * @param klass the target instance class
	 * @return boolean true if this factory support generate the instance of F
	 */
	default boolean support(Class<?> klass) {
		return false;
	}
	/**
	 * @param klass the target class for generate instance
	 * @param params the parameters for generate the instance
	 * @return the instance generated by the factory
	 */
	default F get(Class<F> klass, Object... params) {
		return null;
	}	
	/**
	 * @param key the key of instance 
	 * @param params the parameters for generate the instance
	 * @return
	 */
	F get(S key, Object... params);

}
